### ISSUE TITLE
Bootstrapping in SLC5 image fails

### ISSUE THREAD

**Issue by clelange** [cms-sw/cms-docker#65]
Please let me know if I should post this issue somewhere else.

For an upcoming open data release, I'm trying to install CMSSW_4_2_8_lowpupatch1 into an SLC5 container, but the bootstrap script (or actually `cmspkg.py` with `cmspkg_tag   = "V00-00-37"`) fails. Any idea how to solve it? I don't know why the package size returns an invalid literal (see below).

```
export SCRAM_ARCH=slc5_amd64_gcc434
sh /opt/cms/bootstrap.sh setup -r cms -architecture ${SCRAM_ARCH} -server cmsrep.cern.ch
slc5_amd64
```

Output:

```
Downloading driver file slc5_amd64_gcc434...Done driver slc5_amd64_gcc434.
Downloading driver file slc5_amd64_common ...Downloading driver file common_amd64_common ...Downloading bootstrap core packages...
Reading Package Lists...
Get:1 http://cmsrep.cern.ch cmssw/cms/slc5_amd64_gcc434 external+gcc+4.3.4-cms-1-1.slc5_amd64_gcc434.rpm
Get:2 http://cmsrep.cern.ch cmssw/cms/slc5_amd64_gcc434 external+expat+2.0.0-cms2-1-1.slc5_amd64_gcc434.rpm
Get:3 http://cmsrep.cern.ch cmssw/cms/slc5_amd64_gcc434 external+zlib+1.2.3-cms-1-1.slc5_amd64_gcc434.rpm
Get:4 http://cmsrep.cern.ch cmssw/cms/slc5_amd64_gcc434 external+beecrypt+4.1.2-cms2-1-1.slc5_amd64_gcc434.rpm
Get:5 http://cmsrep.cern.ch cmssw/cms/slc5_amd64_gcc434 external+bz2lib+1.0.5-cms-1-1.slc5_amd64_gcc434.rpm
Get:6 http://cmsrep.cern.ch cmssw/cms/slc5_amd64_gcc434 external+db4+4.4.20-cms-1-1.slc5_amd64_gcc434.rpm
Get:7 http://cmsrep.cern.ch cmssw/cms/slc5_amd64_gcc434 external+elfutils+0.131-cms-1-1.slc5_amd64_gcc434.rpm
Get:8 http://cmsrep.cern.ch cmssw/cms/slc5_amd64_gcc434 external+neon+0.26.3-cms2-1-1.slc5_amd64_gcc434.rpm
Get:9 http://cmsrep.cern.ch cmssw/cms/slc5_amd64_gcc434 external+openssl+0.9.8e-cms4-1-1.slc5_amd64_gcc434.rpm
Get:10 http://cmsrep.cern.ch cmssw/cms/slc5_amd64_gcc434 external+libxml2+2.6.23-cms2-1-1.slc5_amd64_gcc434.rpm
Get:11 http://cmsrep.cern.ch cmssw/cms/slc5_amd64_gcc434 external+rpm+4.4.2.2-cms3-1-1.slc5_amd64_gcc434.rpm
Get:12 http://cmsrep.cern.ch cmssw/cms/slc5_amd64_gcc434 external+apt+0.5.15lorg3.2-cms3-1-1.slc5_amd64_gcc434.rpm
Done.
Unpacking core packages...593260 blocks
593260 blocks
4691 blocks
4691 blocks
360 blocks
360 blocks
1318 blocks
1318 blocks
Can't open /opt/cms/bootstraptmp/BOOTSTRAP/inst/slc5_amd64_gcc434/external/beecrypt/4.1.2-cms2/lib/libbeecrypt.la: No such file or directory.
2340 blocks
2340 blocks
44015 blocks
44015 blocks
5887 blocks
5887 blocks
2848 blocks
2848 blocks
46793 blocks
46793 blocks
35411 blocks
35411 blocks
21602 blocks
21602 blocks
49589 blocks
49589 blocks
Done.
Harvesting system for locally available software...Done.
Initializing local rpm database.../opt/cms/slc5_amd64_gcc434/tmp/system-import /opt/cms
/opt/cms
Done.
Installing packages in the local rpm database...Can't open /opt/cms/slc5_amd64_gcc434/external/beecrypt/4.1.2-cms2/lib/libbeecrypt.la: No such file or directory.
Done
cmspkg setup done.
Installing default packages.Reading Package Lists...
Get:1 http://cmsrep.cern.ch cmssw/cms/slc5_amd64_gcc434 cms+cms-common+1.0-1-1107.slc5_amd64_gcc434.rpm
Building Dependency Tree...
The following NEW packages will be installed:
  cms+cms-common+1.0

0 upgraded, 1 newly installed, 0 removed and 0 not upgraded.
Traceback (most recent call last):
  File "/opt/cms/share/cms/cmspkg/V00-00-37/cmspkg.py", line 1207, in ?
    process(args, opts, cache_dir)
  File "/opt/cms/share/cms/cmspkg/V00-00-37/cmspkg.py", line 1088, in process
    repo.install(pkg, reinstall=opts.reinstall, force=opts.force)
  File "/opt/cms/share/cms/cmspkg/V00-00-37/cmspkg.py", line 675, in install
    size_compress, size_uncompress = self.package_size (pk[1])
  File "/opt/cms/share/cms/cmspkg/V00-00-37/cmspkg.py", line 514, in package_size
    return st.st_size, int(out)
ValueError: invalid literal for int():

There was a problem while installing the default packages
Done
Bootstrap environment to be found in:
### /opt/cms/slc5_amd64_gcc434/external/apt/0.5.15lorg3.2-cms3/etc/profile.d/init.sh
/opt/cms/bootstrap.sh: line 1835: cd: /opt/cms/bootstraptmp/BOOTSTRAP: No such file or directory
```

@katilp

**Comment by smuzaffar** [comment]
assign core
@clelange , I am looking in to it now

**Comment by smuzaffar** [comment]
@clelange , a regexp to find the size of the RPM was not working for some old RPMs. This should be fixed now. Please try again

**Comment by clelange** [comment]
Thanks, that fixed it!
